version: '2'
services:
  micronaut_template:
    image: postgres:15.0
    environment:
      - POSTGRES_DB=micronaut_template
      - POSTGRES_USER=micronaut_template
      - POSTGRES_PASSWORD=password123
      - PGDATA=/var/lib/pgsql_docker/data
    ports:
      - "5432:5432"